name: 'Checkmarx AST CLI Action'
description: 'Simplify Checkmarx Scanning of source code along with Result consumption leveraging Checkmarx AST solution.'
author: 'Checkmarx Technical Services'
inputs:
  base_uri:
    required: true
    description: 'Provide the AST portal URL'
    default: 'http://demo.ast-cloud.com'
  cx_tenant:
    required: true
    description: 'Provide the Tenant for AST portal URL'
    default: 'organization'
  cx_client_id:
    required: false
    description: 'Client ID for AST portal authentication'
    default: ''
  cx_client_secret:
    required: false
    description: 'Secret key for AST portal authentication'
    default: ''
  project_name:
    required: false
    default: ${{ github.repository }} # default repo name
    description: 'Select a Checkmarx Project Name'
  branch:
    required: false
    default: ${{ github.ref }}
    description: 'Branch name'
  github_token:
    required: false
    default: ${{ github.token }}
    description: 'GitHub API Token'
  additional_params:
    required: false
    default: ''
    description: 'Additional parameters for AST scan'
outputs: 
  cxcli:
    description: output from cli
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.base_uri }}
    - ${{ inputs.cx_tenant }}
    - ${{ inputs.cx_client_id }}
    - ${{ inputs.cx_client_secret }}
    - ${{ inputs.github_token }}
    - ${{ inputs.project_name }}
    - ${{ inputs.additional_params }}

  env:
    CX_BASE_URI: "${{ inputs.base_uri }}"
    CX_TENANT: ${{ inputs.cx_tenant }}
    CX_CLIENT_ID: ${{ inputs.cx_client_id }}
    CX_CLIENT_SECRET: ${{ inputs.cx_client_secret }}
    GITHUB_TOKEN: ${{ inputs.github_token }}
    BRANCH: ${{ inputs.branch }}
    PROJECT_NAME: ${{ inputs.project_name }}
    ADDITIONAL_PARAMS: ${{ inputs.additional_params }}

branding:
  icon: 'check'
  color: 'green'
