name: 'Checkmarx AST CLI Action'
description: 'Simplify Checkmarx Scanning of source code along with Result consumption leveraging Checkmarx AST solution.'
author: 'Checkmarx Technical Services'
inputs:
  base_uri:
    required: true
    description: 'Provide the AST portal URL'
    default: 'http://demo.ast-cloud.com'
  cx_client_id:
    required: false
    description: 'Client ID for AST portal authentication'
    default: ''
  cx_client_secret:
    required: false
    description: 'Secret key for AST portal authentication'
    default: ''
  cx_apikey:
    required: false
    description: 'Token for AST portal authentication'
    default: ''
  scan_types:
    required: true
    description: 'Scan types to perform on AST'
    default: ''
  project_name:
    required: false
    default: ${{ github.repository }} # default repo name
    description: 'Select a Checkmarx Project Name'
  github_token:
    required: false
    default: ${{ github.token }}
    description: 'GitHub API Token'
  archive_source:
    required: false
    default: ''
    description: 'Source for the Zip file'
  source_directory:
    required: false
    default: '.'
    description: 'Source for the project directory'
  filter:
    required: false
    default: '*'
    description: 'Project scan filters for AST'
  additional_params:
    required: false
    default: ''
    description: 'Additional parameters for AST scan'
  preset_name:
    required: false
    default: Checkmarx Default # default repo name
    description: 'Checkmarx scan preset value'
outputs: 
  cxcli:
    description: output from cli
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.base_uri }}
    - ${{ inputs.cx_client_id }}
    - ${{ inputs.cx_client_secret }}
    - ${{ inputs.cx_apikey }}
    - ${{ inputs.github_token }}
    - ${{ inputs.scan_types }}
    - ${{ inputs.project_name }}
    - ${{ inputs.archive_source }}
    - ${{ inputs.source_directory }}
    - ${{ inputs.additional_params }}
    - ${{ inputs.filter }}
    - ${{ inputs.preset_name }}

  env:
    CX_BASE_URI: "${{ inputs.base_uri }}"
    CX_CLIENT_ID: ${{ inputs.cx_client_id }}
    CX_CLIENT_SECRET: ${{ inputs.cx_client_secret }}
    CX_TOKEN: ${{ inputs.cx_apikey }}
    GITHUB_TOKEN: ${{ inputs.github_token }}
    SCAN_TYPES: ${{ inputs.scan_types }}
    PROJECT_NAME: ${{ inputs.project_name }}
    ARCHIVE_SOURCE: ${{ inputs.archive_source }}
    SOURCE_DIRECTORY: ${{ inputs.source_directory }}
    ADDITIONAL_PARAMS: ${{ inputs.additional_params }}
    FILTER: ${{ inputs.filter }}
    PRESET_NAME: ${{ inputs.preset_name }}

branding:
  icon: 'check'
  color: 'green'
