name: Checkmarx AST Scan
on:
  pull_request:
    types: [opened, reopened, synchronize] #Types specify which pull request events will trigger the workflow. For more events refer Github Actions documentation.
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkmarx AST CLI Action
        uses: checkmarxDev/ast-github-action@master #Github Action version
        with:
          base_uri: http://demo.ast-cloud.com
          checkamrx_client_id: ${{ secrets.CHECKMARX_CLIENT_ID }}
          checkmarx_secret: ${{ secrets.CHECKMARX_SECRET }}