name: Test github action 

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test if action is working 
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v1
      - name: Run with empty clien and secret
        id: empty_client_secret
        uses: ./
        with:
          project_name: 'test project'
          base_uri: 'https://' 
          cx_client_id: ''
          cx_client_secret: ''
          scan_types: sast
      - name: Check if failed authentication
        if: ${{ contains( steps.empty_client_secret.ouputs.output, 'Failed to authenticate')}}
